project:
  type: website

website:
 title: "Sailor Shift - From Nobody to Somebody"
 navbar:
   left:
   - text: "Project Overview"
     href: "Analysis/Analysis_01/Project_Overview.html"
   - text: "Application"
     href: "Analysis/Analysis_02/Application.html"
   - text: "Poster"
     href: "Analysis/Analysis_03/Poster.html"
   - text: "User Guide"
     href: "Analysis/Data/User_Guide.html"
         
   right:
     - href: index.qmd
       text: Home
     - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

